---
layout: default
theme: jekyll-theme-cayman
title: Trust Coin
description: >
  TrustCoin aims to democratize governance within digital communities by leveraging blockchain technology. 
  This project introduces a decentralized ERC-20 token that empowers community members to participate actively 
  in decision-making through a transparent and secure voting mechanism.
is_project_page: true
repository_url: https://github.com/TrustCoin491/trustcoin491.github.io
---
